### ISSUE TITLE
how about post, put and delete

### ISSUE THREAD

**Issue by amidia** [matthewfedak/slim-3-doctrine-2#1]
hi @matthewfedak 
i tried to create some method for post put and delete but keep failed
here some my code in EmployeeResource
```
...
$employee = $this->entityManager->getRepository('App\Entity\impl\Employee');
$employee->setEmpCode($data[0]['empCode']);
$employee->setEmpFname($data[0]['empFname']);
$employee->setEmpLname($data[0]['empLname']);

$this->entityManager->persist($employee);
$this->entityManager->flush();
```
which part is i got this wrong. and can you point me to the right solution or
can you give some example for another methods?
thanks

**Comment by matthewfedak** [comment]
`
// POST (insert new record)

$employee = new \App\Entity\impl\Employee();
$employee->setEmpCode($data[0]['empCode']);
$employee->setEmpFname($data[0]['empFname']);
$employee->setEmpLname($data[0]['empLname']);
$this->entityManager->persist($employee);
$this->entityManager->flush();

// PUT (update record)

$id = '23; // i.e. some employee id
$employee = $this->entityManager->getRepository('App\Entity\impl\Employee')->find($id);
$employee->setEmpCode($data[0]['empCode']);
$employee->setEmpFname($data[0]['empFname']);
$employee->setEmpLname($data[0]['empLname']);
$this->entityManager->persist($employee);
$this->entityManager->flush();

// DELETE (delete a record)

$id = '23; // i.e. some employee id
$employee = $this->entityManager->getRepository('App\Entity\impl\Employee')->find($id);
$this->entityManager->remove($employee);
$this->entityManager->flush();
`

**Comment by amidia** [comment]
awesome...
thanks @matthewfedak.
